# Generated by Django 4.2.7 on 2023-11-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='book_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='distribution_expense',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='subtitle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
